# Default configuration
spring:
  application:
    name: recipe-api
  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

app:
  name: Recipe API
  version: 1.0.0

jwt:
  secret: KETqKacftjmGhmQirL6kG7NcJ+gl3+AdeivvVPUknbfg4+jIK8Bg7V2K1PLJ4sXksc/wwiKMzxI870KF2bCPgg==
  expiration: 86400000  # 24 hours in milliseconds